ALTER TABLE public.candidates
  ADD COLUMN IF NOT EXISTS marital_status text,
  ADD COLUMN IF NOT EXISTS spouse_name text,
  ADD COLUMN IF NOT EXISTS is_cooperative_member boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS cooperative_name text,
  ADD COLUMN IF NOT EXISTS target_vehicle_price_rwf numeric,
  ADD COLUMN IF NOT EXISTS offers_collateral boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS collateral_description text,
  ADD COLUMN IF NOT EXISTS collateral_value_rwf numeric,
  ADD COLUMN IF NOT EXISTS listed_on_crb boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS crb_resolution_notes text,
  ADD COLUMN IF NOT EXISTS other_loan_bank text,
  ADD COLUMN IF NOT EXISTS other_loan_repayment_source text,
  ADD COLUMN IF NOT EXISTS previously_drove_for_service boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_spouse_id boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_loan_application_letter boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_tax_clearance boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_marital_status_proof boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_proforma_invoice boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_deposit_proof boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_momo_statement boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_yego_history boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_cooperative_letter boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_previous_vehicle_docs boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS doc_two_passport_photos boolean NOT NULL DEFAULT false;